### ISSUE TITLE
Deadtime setting

### ISSUE THREAD

**Issue by andree182** [SVentas/EvvGC-PLUS#5]
I read through the tutorial again, and while my board seems to work with 1000ns dead time fine (at least no excess heat so far), the set-dt-and-reboot scheme seems a bit unnecessary? Do you see a problem (like in "it could burn out easily"), if we reworked the configurator (+a bit of the firmware) to:

1) set all parameters to 0
2) set deadtime
3) set all parameters back to configured values? Or do you think the parameters are so dependent on deadtime, it makes more sense to keep them reset to 0?

Other way would be to reboot the board automagically after setting deadtime (+warn user to wait).

**Comment by SVentas** [comment]
Hi, andree182,
You have to reboot the board because I use LOCK Level 1 of TIMx_BDTR register (break and dead-time register) of TIM1&TIM8 (see **pwmio.c**). Data sheet says:
"*Note: The LOCK bits can be written only once after the reset. Once the TIMx_BDTR register has been written, their content is frozen until the next reset.*"
You can remove LOCK Level from the code, but then reliability/safety of TIM1&TIM8 based PWM drivers will be reduced if something  wrong happens.
Perhaps You must stop timers first and then try to change dead-time. I don't know what consequencies will be if dead-time will be changed on the fly...
It is not necessary to set all parameters to 0. Initial values are equal to zero because I want to filter out users that are not smart enough to configure their boards properly and prevent boards from damage :smiley: .
Remember this is an **EXPERIMENTAL** firmware and I think I will not be happy if You decide to remove LOCK Level :smiley: ! I know that Yaw channel is not safe compared to pitch or roll, but usually I do not use yaw.
In the current code, power settings depend on dead-time values in very nonlinear fashion. Perhaps it is worth to rewrite that part, but I am not going to do that, because now I am interested in adding the second IMU.
I see You are trying to make EvvGC-PLUS user friendly :+1: .

**Comment by andree182** [comment]
Ah, ok, I didn't get as far as reading datasheet for the used PWM registers :) So, sorry - I thought it's just some "interface decision", and that the PWM outputs could be just "stopped", settings reapplied, and then restarted... But from the above it seems like it's a good idea to keep as-is, for now.

Anyhow, the values are once per board-gimbal combination - so I guess there's no need to scratch our heads too much over this. Maybe I'll just add that "warning" somewhere into GUI, that board needs reboot.

Of course - you are the maintainer, so feel free to reject commits from me, no hard feelings - with github it's easy to keep my private copy... :) As said elsewhere though, I like this project code (much more than original), so I would like if it was more used (hence the usability improvement attempts)... Though I'm not sure whether the board has a future - as even you said it's got somewhat flawed design. But that's another discussion.

**Comment by andree182** [comment]
https://github.com/andree182/EvvGC-PLUS/commit/e3f3b5fdb793dc8f8e054d5b6e1cae6f94b80ac3 ... I'll create a pull request... one of these days :)
